services:
  backend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - library_net
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  library_net:
    external: true